source 'https://github.com/CocoaPods/Specs.git'


target 'DemoPodCreate_Example', :exclusive => true do
  pod 'DemoPodCreate', :path => '../'
end

target 'DemoPodCreate_Tests', :exclusive => true do
  pod 'DemoPodCreate', :path => '../'

  
end
